######################################################################
# Automatically generated by qmake (2.01a) Wed Mar 31 10:32:23 2021
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .


UI_DIR       = ./build
MOC_DIR      = ./build
OBJECTS_DIR  = ./build


# Input
HEADERS += fmt_format.h fmt_posix.h Glog.h Svar.h utils_debug.h
SOURCES += fmt_format.cpp fmt_posix.cpp test_log.cpp utils_debug.cpp
