######################################################################
# Automatically generated by qmake (3.0) Wed Mar 18 17:00:32 2020
######################################################################

TEMPLATE = app
TARGET = draw_map
QT += gui widgets

INCLUDEPATH += .

# Input
HEADERS += map_viewer.h
SOURCES += draw_map.cpp map_viewer.cpp
